### ISSUE TITLE
Tag bugs: documentation, solution and nextproblem at the beginning of the file

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#59] opened 2018-09-04 13:01 UTC
I think some issues are remaining.

1. I have tested the tag feature, but I think there are still some problems. I have only tested with one tag, not multiple tags. As before, my exercises are in an external file: ``databaseNombres.tex``

There are a lot of problems, only two are tagged. I have added before two problems:

    \nextproblem{tag=fiche1}

To select the problems in my main file:

    \makeset[nohead]{myExerciseSet}{databaseNombres}
    \buildtags{fiche1}{myExerciseSet}

I get the following error if I compile:

    ERROR: Package listofitems Error: Empty list ignored, nothing to do.

It only happens if the first problem of the external file doesn't begin with a ``\nextproblem``. If I add one, it doesn't matter how much problems are tagged. 

2. After reading section 2.9 of your documentation, If I have

     ``\makeset[nohead]{myExerciseSet}{databaseNombres}``

I would create the exercise set with

    \buildtags{fiche1}{databaseNombres}

instead of 

    \buildtags{fiche1}{myExerciseSet}

which doesn't work. 

3. Then if I use ``\DisplaySolutions``, the String "Solution" is written multiple times. I assume, a problem is displayed if it's the chosen tag. If the problem doesn't have the tag, only the title "Solution" is printed.

**Comment by Strauman** [comment] 2018-09-04 18:51
@tristelune1 We're a great team! Your testing helps me out **SO** much! Thank you! This should be fixed in b86!

**Comment by tristelune1** [comment] 2018-09-05 15:02
@Strauman Yes, it's a pleasure! I'm eager to use your package with all features! I think there is more to come before you release this version, stay tuned ;-)

I've tested, but unfortunately it doesn't work. Yesterday I tried and I have in mind it compiled without problem, but every problem were displayed. Today I get an error after the compilation:
```
ERROR: Extra \fi.

--- TeX said ---
\At@DecideProblemDisplay ...pthidestrue } \fi \fi 
                                                  
l.31 \begin{problem}
                    
--- HELP ---
From the .log file...

I'm ignoring this; it doesn't match any \if.
```
I let you check, I don't know the tex syntax, but probably you ended an if...else statement with two \fi instead of one \fi.

Your documentation is good now!

**Comment by Strauman** [comment] 2018-09-05 18:57
@tristelune1 Can't seem to reproduce?

**Comment by Strauman** [comment] 2018-09-05 19:03
@tristelune1 I just made a rebuild (maybe something happened during the compilation or the like). You can find build 87 [here](https://raw.githubusercontent.com/Strauman/exercisebank/0.2.1b87-prerelease/exercisebank.sty)

**Comment by tristelune1** [comment] 2018-09-05 20:44
It doesn't work either with the new build. I have to investigate. But before, please take a look at [#60](https://github.com/Strauman/exercisebank/issues/60). Perhaps it's the reason why I have the problem.

**Comment by tristelune1** [comment] 2018-09-06 20:14
Bug [#60](https://github.com/Strauman/exercisebank/issues/60) is solved, but it still doesn't work. With a ``buildset`` instruction everything works fine, excepted some blank pages, but that's another problem. As soon as I use ``buildtags`` with two different external files:

- for one I get an error
- for the other it's compiled without an error, but the tagged problems are not selected. I'll try with simplified files and I'll send them to you, unless I discover my error.

**Comment by Strauman** [comment] 2018-09-07 06:39
I have to be able to reproduce it, or else I don't know what to fix :/

**Comment by Strauman** [comment] 2018-09-07 06:42
I'm reproducing it!

**Comment by Strauman** [comment] 2018-09-07 06:54
Should be working in build 89!

**Comment by tristelune1** [comment] 2018-09-07 12:35
HHmm, sorry to be the killjoy or partypooper... (It's a new word for me, I assume it's the right one!). 

I think the selection by tag works, but one of our friend seems to be back. If the file doesn't begin with ``\nextproblem`` I have an error. Do you have the same ?

**Comment by Strauman** [comment] 2018-09-07 15:27
@tristelune1 I think those are the right words, yes. Actually - I think you're the party saver, because without you I'd probably publish a version containing a lot of bugs 🥇

**Comment by Strauman** [comment] 2018-09-07 15:33
it was #49, but I actually don't have that error!

**Comment by Strauman** [comment] 2018-09-07 15:39
I was able to reproduce it. I think

**Comment by Strauman** [comment] 2018-09-07 15:58
Can't reproduce it.

**Comment by tristelune1** [comment] 2018-09-07 18:36
Thank your for your comment, I appreciate it a lot  :smiley: !! 

No, this bug [#59](https://github.com/Strauman/exercisebank/issues/59). Take for example this master file (I let you adapt what is necessary):

```
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{etoolbox}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{exercisebank}

\exercisebanksetup{exercise
  directory=/home/user/Mes_Documents/prof/cours_exercices/bank/,
figure root
directory=/home/user/Mes_Documents/prof/cours_images/math/,
part problems=Off}

\makeset[nohead]{myExerciseSet}{databasedummy}

\DisplaySolutions
\ShowNumbers
\translateExBank{Problem=Exercice}
\begin{document}
\date{}

\buildtags{fiche1}{myExerciseSet}
 
\end{document}
```

Then this external file (`databasedummy`):

```
\nextproblem{tag=fiche1}
\begin{problem}
  Problem 1
\end{problem}
\begin{solution}
  Solution 1
\end{solution}
\nextproblem{tag=fiche1}
\begin{problem}
  Problem 2
\end{problem}
\begin{solution}
  Solution 2
\end{solution}
```

1. Compile the main file. It works without a problem.
2. Delete the first `nextproblem` of the external file. Compile the main file. There is an error.

**Comment by Strauman** [comment] 2018-09-08 09:51
Yup. That reproduces it! 👍

**Comment by Strauman** [comment] 2018-09-08 11:04
Should be fixed in b90

**Comment by tristelune1** [comment] 2018-09-08 16:02
There is no more error.... but unfortunately, it doesn't work as expected. Take my `databasedummy` and my main file. Delete the first `nextproblem` of `databasedummy`. I expect that only the second problem is displayed. For me both problem are displayed.

**Comment by Strauman** [comment] 2018-09-08 19:51
@tristelune1 This should be a new problem. I made one: #64. The reason I want it in a different issue is so that if it arises again, I can easily see what I did to fix it the previous time. Also it's easier for me, you and anyone else to keep track of what is fixed and what isn't.

**Comment by Strauman** [comment] 2018-09-16 08:32
Great!

**Comment by Strauman** [comment] 2018-09-16 08:32
(You can close issues that you opened too :) )

**Closed by Strauman** 2018-09-16 08:32 UTC
