### ISSUE TITLE
Best candidate to test and use v0.2.3-prerelease?

### ISSUE THREAD

**Issue by prismv** [Strauman/exercisebank#90] opened 2018-11-28 18:37 UTC
Dear Andreas,

today I was upgrading from build 106 to build 110, and found out that it seems to be broken somehow (e.g. display solutions). Currently v0.2.3-prerelease - Build 108 seems fine. 

I saw then that you actually logged latest two releases as 'experimental', but this is not obvious from README.md content.

Thanks for your work.

Regards
Ralf

**Comment by Strauman** [comment] 2018-11-28 19:14
Hello Ralf!
So currently CTAN has build 97, and any release not on CTAN should in one way or another be considered experimental. However when I write `experimental` in the release, it is most likely some issues! I'm trying to keep the prereleases as bug-free as possible though, but no guarantees!

Would you mind specifying what is wrong with build 110? You say `\DisplaySolutions` doesn't work, and I can reproduce that, and will fix it.

Are there any other things you found that was broken? I need to reproduce any issues, so could you please provide an [MVCE](https://stackoverflow.com/help/mcve)? . The easiest would be writing the code here. Use three backticks, like these: ` ``` YOUR CODE ``` ` to format it nicely! You could alternatively upload code here from files by dragging them into where you write comments.

Thank you for reporting! :)

**Comment by Strauman** [comment] 2018-11-28 19:19
@prismv as it turns out, the solutions are shown, but the wrong warning message is showing: 

> `Hiding solutions. Show them with \DisplaySolutions`

Is this the same as your problem?

**Comment by Strauman** [comment] 2018-11-28 19:30
Released [build 111](https://github.com/Strauman/exercisebank/releases/tag/0.2.3b111-experimental): Would you mind to check if this works as expected?

**Comment by prismv** [comment] 2018-12-04 23:53
[test.zip](https://github.com/Strauman/exercisebank/files/2646589/test.zip)

Sorry for delay. Attached file shows that also with build 111 instead of solution text only a 0 is inserted. Build 108 works as expected.

**Comment by Strauman** [comment] 2018-12-07 10:40
Thank you, @prismv. Check out [Build 113](https://github.com/Strauman/exercisebank/releases/tag/0.2.3b113-experimental)!

**Comment by prismv** [comment] 2018-12-08 12:03
Dear @Strauman, I checked the most recent 0.2.3b115-prerelease and the problem with no display of solution is solved. So I can go on testing the 0.2.3+ release with the latest version. Great!

Best regards

**Comment by Strauman** [comment] 2019-02-15 08:31
I'm closing this :)
When you are using the latest prereleases and/or experimental versions, please let me know?
Even when it works, it's nice to know :)

**Closed by Strauman** 2019-02-15 08:31 UTC
