### ISSUE TITLE
Undefined control sequence when I redefine problem and solution in Chinese

### ISSUE THREAD

**Issue by mayoutu** [Strauman/exercisebank#9] opened 2018-04-06 07:43 UTC
![fb2](https://user-images.githubusercontent.com/38101830/38408652-fb82d99e-396d-11e8-9f9f-9cb5987f8bef.png)
When I redefine problem and solution to be P and S respectively, there is no problem; but when I redefine them to be in Chinese, it says undefined control sequence.

I'm using other packages and it has no trouble compiling the Chinese characters.

**Comment by Strauman** [comment] 2018-04-06 08:56
For [0.1.0](https://github.com/Strauman/exerciseBank/milestone/1) (version coming out beginning of **next week**) you can try the following as a workaround:

```
\documentclass{amsart}
\usepackage{exercisebank}
\makeset{gzh1}{...}
...
%% TRY THIS WHEN 0.1.0 IS OUT %%
\makeatletter
\gdef\exbank@opt@problemHeader{\normalfont\Large\bfseries TRANSLATION~\theproblemcounter}
\gdef\exbank@opt@solutionHeader{\large{\textbf{TRANSLATION}}}
\makeatother
%% /TRY THIS %%
\begin{document}
  \buildset{gzh1}
\end{document}
```

**Comment by Strauman** [comment] 2018-04-06 08:57
I suspect, for the real fix, that the problem is that pgfkeys do not allow Chinese characters for some reason. I will try to investigate later.

**Comment by Strauman** [comment] 2018-04-06 16:49
@mayoutu - you can try the workaround now (if you download the "beta" version). You can download it [here](https://github.com/Strauman/exerciseBank/blob/master/exercisebank.zip), or from the front page of this repo :)

**Comment by mayoutu** [comment] 2018-04-07 05:57
I can wait until the next version comes out. No hurry!

**Comment by Strauman** [comment] 2018-04-12 13:17
I'm closing this for now. Re open this if the work around did not work?

**Closed by Strauman** 2018-04-12 13:17 UTC
Labels: bug
